#! /bin/bash

#intergrated test for userhandlling using shell script
#check the registration
curl -k --data "username=itest2&password=itest2&displayName=itest&aboutMe=itest&maxTravelDistance=10&latitude=40&longitude=-74&swimming=1&reading=1&bike=1&hiking=1&camp=1&dance=1&run=1&games=1&bowl=1&basketball=1&football=1&baseball=1&program=1&TV=1&movies" https://199.98.27.118:8080/register

#check the login
curl -k -d "username=itest2&password=itest2&submit=Login" --dump-header headers https://199.98.27.118:8080/login
curl -k -L -b headers https://199.98.27.118:8080/home

response=$(curl -k -H "Accept: application/json" -H "Content-Type: application/json" -X GET https://199.98.27.118:8080/user/itest2)
itest2={"DisplayName":"itest","AboutMe":"itest","PhotoPath":null,"Messages":"[]","self":false}

if (itest2==response); 
then
echo "Working"
else
echo "Not Working"
fi


#result directed to a file method
#curl -k -H "Accept: application/json" -H "Content-Type: application/json" -X GET https://199.98.27.118:8080/friends >> C:\cygwin64\home\Lenovo
