package com;

import static spark.Spark.*;

public class MatchApp {

    // Declare dependencies (i.e. classes, interfaces) [OPTIONAL]

    public static void main(String[] args) {

        // Instantiate dependencies (create objects) [OPTIONAL]

        /**
         * This directory will contain all static files that will be served
         * These are files that aren't generated by the server, but are prest and loaded
         * e.g. HTML forms, images, CSS style sheets, static javascript files
         * Home page, login, register pages can be static?
         * Profile/Friendslist, Friend profile pages can not?
         */
        String staticFilesDir = "src/main/resources/";


        // Configure Spark's embedded Jetty webserver
        port(8080);     // To test routes: localhost:8080/<routeURL>
        staticFiles.location(staticFilesDir);   // Set static files directory


        // Set up before filters [OPTIONAL]


        // Set up routing
        get("/test", (req, res)->"Successfully reached MATCH - Friend Matching Platform.\n");

        get("/user/:name", (req,res)->{
            return "This is the user profile of: "+ req.params(":name");
        });

        post("/login",(req,res)-> {
            String name = req.queryParams("username");
            String pass = req.queryParams("password");
            if (name.equals("Ivan") && pass.equals("123van"))
                return "Correct! Your username is " + name + " and your password is " + pass + ".";
            else
                return "You entered the username " + name + " and the password " + pass + ". It's wrong. Try \"Ivan\" and \"123van\".";

        });

        post("/register",(req,res)-> {
            String name = req.queryParams("username");
            String pass = req.queryParams("password");
            String displayName = req.queryParams("displayName");
            String maxTravelDistance = req.queryParams("maxTravelDistance");
            String aboutMe = req.queryParams("aboutMe");
            return "Registration successful!";
        });

            // May need a logout route - not sure yet.
            // Upload profile pic route - http://sparkjava.com/documentation#javadoc


        // Set up after filters [OPTIONAL]


        // Initialize and test database
    }
}